export enum CargoTransportationKind {
  CargoTaxi = 'Грузовое такси',
  ApartmentMoving = 'Квартирный переезд',
  OfficeMoving = 'Офисный переезд',
  FurnitureTransport = 'Перевозка мебели',
  FoodTransport = 'Перевозка продуктов',
  IntercityTransport = 'Междугородние перевозки',
  InternationalTransport = 'Международные перевозки',
  LCLTransport = 'Доставка сборных грузов',
  LivestockTransport = 'Перевозка лошадей и крупного рогатого скота',
  PersonalItemsTransport = 'Перевозка личных вещей',
  ApplianceTransport = 'Перевозка бытовой техники',
  FruitTransport = 'Перевозка фруктов',
  VegetableTransport = 'Перевозка овощей',
  CountryHouseMoving = 'Дачный переезд',
  WarehouseMoving = 'Переезд склада',
  PianoTransport = 'Перевозка пианино',
  SafeTransport = 'Перевозка сейфов',
  RefrigeratorTransport = 'Перевозка холодильников',
  EquipmentTransport = 'Перевозка оборудования',
  ConstructionMaterialsTransport = 'Перевозка строительных материалов',
  MotorcycleTransport = 'Перевозка мотоциклов',
}
