export enum SpecialType {
  Excavator = 'Excavator',
  AerialPlatform = 'AerialPlatform',
  TruckCrane = 'TruckCrane',
  TruckFuel = 'TruckFuel',
  Bulldozer = 'Bulldozer',
  HydraHammer = 'HydraHammer',
  Grader = 'Grader',
  CragLoader = 'CragLoader',
  RoadRoller = 'RoadRoller',
  MiniLoader = 'MiniLoader',
  MiniExcavator = 'MiniExcavator',
  WasteCar = 'WasteCar',
  DumpTruck = 'DumpTruck',
  Tractor = 'Tractor',
  FrontLoader = 'FrontLoader',
  TruckCement = 'TruckCement',
  ExcavatorLoader = 'ExcavatorLoader',
  Yamobur = 'Yamobur'
}
