// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fleetfinder.service.main.domain.Enums.Common;
using fleetfinder.service.main.domain.Enums.Transport;
using fleetfinder.service.main.domain.Enums.Transport.Cargo;
using fleetfinder.service.main.domain.Enums.Transport.Passenger;
using fleetfinder.service.main.domain.Enums.Transport.Special;
using fleetfinder.service.main.infrastructure.Common.DbContexts;

#nullable disable

namespace fleetfinder.service.main.infrastructure.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    [Migration("20260807165856_RemoveOrders")]
    partial class RemoveOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cargo_body_kind", new[] { "agricultural_grain_vehicle", "auto_train", "beam_vehicle", "cargo_passenger", "chip_car", "container_vehicle", "coupling", "curtain_sider", "feed_vehicle", "flatbed_vehicle", "flour_vehicle", "glass_vehicle", "hydraulic_lift", "insulated_vehicle", "isothermal_vehicle", "light_trailer", "livestock_vehicle", "open_vehicle", "oversized_vehicle", "panel_vehicle", "pickup", "pipe_vehicle", "pyramid", "refrigerator", "roll_vehicle", "semi_trailer", "solid_metal", "tank_container", "timber_vehicle", "tractor_unit", "trailer_truck", "van" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cargo_transportation_kind", new[] { "apartment_moving", "appliance_transport", "cargo_taxi", "construction_materials_transport", "country_house_moving", "equipment_transport", "food_transport", "fruit_transport", "furniture_transport", "intercity_transport", "international_transport", "lcl_transport", "livestock_transport", "motorcycle_transport", "office_moving", "personal_items_transport", "piano_transport", "refrigerator_transport", "safe_transport", "vegetable_transport", "warehouse_moving" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cargo_type", new[] { "t1", "t10", "t2", "t20", "t3", "t5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "experience_work", new[] { "less_year1", "more_year10", "year1", "year2", "year3", "year4", "year5", "year6", "year7", "year8", "year9" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_facilities", new[] { "comfortable", "economy", "standard" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_option", new[] { "air_conditioner", "audio_system_and_microphone", "climate_control", "individual_lighting", "large_luggage_compartments", "monitor_and_dvd", "safety_belts", "seat_heating", "sleeping_places", "spacious_salon", "toilet", "ventilation_system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_rental_duration", new[] { "long_term", "one_day", "per_day", "per_hour", "per_month" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_transportation_kind", new[] { "abroad_trips", "airport_transfer", "car_home", "children", "corporate", "courier", "employee_delivery", "excursion", "funeral", "intercity", "medical", "order", "party_bus", "pet", "tourists", "vip", "wedding" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "passenger_type", new[] { "bus", "limousine", "minivan", "shiftw", "taxi", "water" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "card_payment", "cash", "cash_and_non_cash", "non_cash" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_order", new[] { "installment_payment", "payment_upon_delivery", "prepayment" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "region", new[] { "bender", "camenka", "dubasari", "grigoriopol", "ribnitsa", "slobozia", "tiraspol" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "special_type", new[] { "aerial_platform", "bulldozer", "crag_loader", "dump_truck", "excavator", "excavator_loader", "front_loader", "grader", "hydra_hammer", "mini_excavator", "mini_loader", "road_roller", "tractor", "truck_cement", "truck_crane", "truck_fuel", "waste_car", "yamobur" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "state", new[] { "actual", "archived" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Cargo.CargoTransport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<ExperienceWork?>("ExperienceWork")
                        .HasColumnType("experience_work");

                    b.Property<PaymentMethod?>("PaymentMethod")
                        .HasColumnType("payment_method");

                    b.Property<PaymentOrder?>("PaymentOrder")
                        .HasColumnType("payment_order");

                    b.Property<Region>("Region")
                        .HasColumnType("region");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<CargoTransportationKind?>("TransportationKind")
                        .HasColumnType("cargo_transportation_kind");

                    b.Property<CargoType>("Type")
                        .HasColumnType("cargo_type");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("YearIssue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CargoTransport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Cargo.CargoTransportImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<long>("TransportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("CargoTransportImage");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int?>("CountSeats")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<ExperienceWork?>("ExperienceWork")
                        .HasColumnType("experience_work");

                    b.Property<PassengerFacilities?>("Facilities")
                        .HasColumnType("passenger_facilities");

                    b.Property<decimal?>("MinOrderTime")
                        .HasColumnType("numeric");

                    b.Property<PassengerOption?>("Option")
                        .HasColumnType("passenger_option");

                    b.Property<PaymentMethod?>("PaymentMethod")
                        .HasColumnType("payment_method");

                    b.Property<PaymentOrder?>("PaymentOrder")
                        .HasColumnType("payment_order");

                    b.Property<Region>("Region")
                        .HasColumnType("region");

                    b.Property<PassengerRentalDuration?>("RentalDuration")
                        .HasColumnType("passenger_rental_duration");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PassengerTransportationKind?>("TransportationKind")
                        .HasColumnType("passenger_transportation_kind");

                    b.Property<PassengerType>("Type")
                        .HasColumnType("passenger_type");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("YearIssue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PassengerTransport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransportImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<long>("TransportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("PassengerTransportImage");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Special.SpecialTransport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<ExperienceWork?>("ExperienceWork")
                        .HasColumnType("experience_work");

                    b.Property<PaymentMethod?>("PaymentMethod")
                        .HasColumnType("payment_method");

                    b.Property<PaymentOrder?>("PaymentOrder")
                        .HasColumnType("payment_order");

                    b.Property<Region>("Region")
                        .HasColumnType("region");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<SpecialType>("Type")
                        .HasColumnType("special_type");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("YearIssue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SpecialTransport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Special.SpecialTransportImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<long>("TransportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransportId");

                    b.ToTable("SpecialTransportImage");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<State>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("state")
                        .HasDefaultValueSql("'actual'::state");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc', current_timestamp)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Cargo.CargoTransport", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Users.User", "User")
                        .WithMany("CargoTransports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("fleetfinder.service.main.domain.Transport.Cargo.Body", "Body", b1 =>
                        {
                            b1.Property<long>("CargoTransportId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Height")
                                .HasColumnType("numeric");

                            b1.Property<CargoBodyKind?>("Kind")
                                .HasColumnType("cargo_body_kind");

                            b1.Property<decimal?>("Length")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("LoadCapacity")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Volume")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Width")
                                .HasColumnType("numeric");

                            b1.HasKey("CargoTransportId");

                            b1.ToTable("CargoTransport");

                            b1.WithOwner()
                                .HasForeignKey("CargoTransportId");
                        });

                    b.OwnsOne("fleetfinder.service.main.domain.Bases.Price", "Price", b1 =>
                        {
                            b1.Property<long>("CargoTransportId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("PerHour")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerKm")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerShift")
                                .HasColumnType("numeric");

                            b1.HasKey("CargoTransportId");

                            b1.ToTable("CargoTransport");

                            b1.WithOwner()
                                .HasForeignKey("CargoTransportId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Cargo.CargoTransportImage", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Transport.Cargo.CargoTransport", "Transport")
                        .WithMany("Images")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransport", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Users.User", "User")
                        .WithMany("PassengerTransports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("fleetfinder.service.main.domain.Bases.Price", "Price", b1 =>
                        {
                            b1.Property<long>("PassengerTransportId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("PerHour")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerKm")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerShift")
                                .HasColumnType("numeric");

                            b1.HasKey("PassengerTransportId");

                            b1.ToTable("PassengerTransport");

                            b1.WithOwner()
                                .HasForeignKey("PassengerTransportId");
                        });

                    b.OwnsOne("fleetfinder.service.main.domain.Transport.Passenger.Size", "Size", b1 =>
                        {
                            b1.Property<long>("PassengerTransportId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("Height")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Length")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("Width")
                                .HasColumnType("numeric");

                            b1.HasKey("PassengerTransportId");

                            b1.ToTable("PassengerTransport");

                            b1.WithOwner()
                                .HasForeignKey("PassengerTransportId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Size")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransportImage", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransport", "Transport")
                        .WithMany("Images")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Special.SpecialTransport", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Users.User", "User")
                        .WithMany("SpecialTransports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("fleetfinder.service.main.domain.Bases.Price", "Price", b1 =>
                        {
                            b1.Property<long>("SpecialTransportId")
                                .HasColumnType("bigint");

                            b1.Property<decimal?>("PerHour")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerKm")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("PerShift")
                                .HasColumnType("numeric");

                            b1.HasKey("SpecialTransportId");

                            b1.ToTable("SpecialTransport");

                            b1.WithOwner()
                                .HasForeignKey("SpecialTransportId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Special.SpecialTransportImage", b =>
                {
                    b.HasOne("fleetfinder.service.main.domain.Transport.Special.SpecialTransport", "Transport")
                        .WithMany("Images")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Users.User", b =>
                {
                    b.OwnsOne("fleetfinder.service.main.domain.Users.Contact", "Contact", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("PhoneTelegram")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneViber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneWhatsapp")
                                .HasColumnType("text");

                            b1.Property<string>("WorkingMode")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("fleetfinder.service.main.domain.Users.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("First")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Second")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Surname")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("fleetfinder.service.main.domain.Users.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<DateTime?>("ExpiryTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Value")
                                .HasColumnType("text");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Cargo.CargoTransport", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Passenger.PassengerTransport", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Transport.Special.SpecialTransport", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("fleetfinder.service.main.domain.Users.User", b =>
                {
                    b.Navigation("CargoTransports");

                    b.Navigation("PassengerTransports");

                    b.Navigation("SpecialTransports");
                });
#pragma warning restore 612, 618
        }
    }
}
